from FeatureExtractor import FeatureExtractor
from BagFeatureExtractor import BagFeatureExtractor
from TfidfFeatureExtractor import TfidfFeatureExtractor
from WordEmbeddingFeatureExtractor import WordEmbeddingFeatureExtractor
from SennaFeatureExtractor import SennaFeatureExtractor